### PR TITLE
Gs 1.7.1 - ACL 2.1.1

### PR DESCRIPTION
**Pull request by jemacchi**
Resolves issue #198

### CODE REVIEW

**Comment by groldan** [comment]
@jemacchi Updated the PR to use ACL 2.1.1 after the better fix for the swaggerui to work properly behind a reverse proxy (https://github.com/geoserver/geoserver-acl/pull/60)

**Review by groldan — APPROVED** [review]
Tested.

**Comment by jemacchi** [comment]
I did my own test and it works fine. great @groldan !

> @jemacchi Updated the PR to use ACL 2.1.1 after the better fix for the swaggerui to work properly behind a reverse proxy ([geoserver/geoserver-acl#60](https://github.com/geoserver/geoserver-acl/pull/60))
> 
> Steps to verify:
>

**Comment by danduk82** [comment]
Great thanks :)

**Pull request merged**
